name: game
version: 0.1.1+2
publish_to: none
description: Quick Push Game
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  get: 4.6.6
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  animated_background: ^2.0.0
  flame_audio: ^2.1.6
  google_mobile_ads: ^4.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  in_app_purchase: ^3.1.13
  another_flutter_splash_screen: ^1.2.0
  animated_splash_screen: ^1.3.0
  connectivity_wrapper: ^1.1.4
  fluttertoast: ^8.2.4
  icons_launcher: ^2.1.7
  rename_app: ^1.3.2
  animated_toast_list: ^1.0.2
  toasted: ^1.0.0

  

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audio/

  fonts:
    - family: Cute-Dolphin-Regular
      fonts:
        - asset: fonts/Cute-Dolphin-Edited.ttf
          weight: 400
    - family: LEMONMILK-Regular
      fonts:
        - asset: fonts/LEMONMILK-Regular.otf
          weight: 400
